# Configurações do banco de dados
spring.application.name=jpa
spring.datasource.url=jdbc:mysql://localhost:3306/creditcard
spring.datasource.username=mariah
spring.datasource.password=130127
spring.jpa.properties.hibernate.jdbc.lab.non_contextual_creation=true
#JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
@EnableJpaRepositories(
basePackages = "org.jala.university.domain.repository",
excludeFilters = @ComponentScan.Filter(
type = FilterType.ASSIGNABLE_TYPE,
classes = CreditCardRepository.class
